"@FILE-NAME@"       tpl-file-name
"@USER-LOGIN@"      tpl-user-login
"@USER-NAME@"       tpl-user-name
"@USER-MAIL@"	tpl-user-mail
"@DATE-STAMP@"      tpl-date-stamp
"@HOST@"            tpl-host
"@IFDEF@"           (concat (upcase (subst-char-in-string ?- ?_ (substring tpl-file-name 0 -3))) "_HH_")
"@ENDIFDEF@"        (concat "!" (upcase (subst-char-in-string ?- ?_ (substring tpl-file-name 0 -3))) "_HH_")
"@YEAR@"	    tpl-year
"@Id@"              (concat () "Id")
