#!/bin/sh
## kshprompt for ctafconf in /home/ctaf/.ctafconf
##
## Made by GESTES Cedric
## Login   <ctaf@epita.fr>
##
## Started on  Thu Oct  6 05:12:07 2005 GESTES Cedric
## Last update Thu Oct  6 06:35:14 2005 GESTES Cedric
##
##CTAFCONF

col_trans=$'\E[0m'
col_black=$'\E[30m'
col_red=$'\E[31m'
col_green=$'\E[32m'
col_yellow=$'\E[33m'
col_blue=$'\E[34m'
col_magenta=$'\E[35m'
col_cyan=$'\E[36m'
col_white=$'\E[37m'

PS1="$col_red`logname`@$col_yellow`hostname -s` \
$col_magenta[$col_white$?$col_magenta] [$col_blue`pwd`$col_magenta]$col_white
k$col_green$ $col_trans"

