#!/bin/sh
## kshrc for ctafconf in /home/ctaf/.ctafconf
##
## Made by GESTES Cedric
## Login   <ctaf@epita.fr>
##
## Started on  Thu Oct  6 04:55:46 2005 GESTES Cedric
## Last update Fri May  5 17:27:10 2006 GESTES Cedric
##
##CTAFCONF

# skip remaining setup if shell non-interactive
[[ -o interactive ]] || return 0
[ a$HOST = agate-ssh ] && return 0

echo -n "shell: ksh, "
cat ~/.ctafconf/etc/shell/motd

#date reminder
~/.ctafconf/bin/ct-date

# turn on command line editing mode
set -o emacs
#set -o vi-tabcomplete   # tab filename completion ON!

alias source=.

if [ -f ~/.ctafconf/etc/ksh/kshprompt ]; then
    . ~/.ctafconf/etc/ksh/kshprompt
fi

if [ -f ~/.ctafconf/etc/shell/globalenv ]; then
    . ~/.ctafconf/etc/shell/globalenv sh
fi

if [ -f ~/.ctafconf/etc/shell/alias ]; then
    . ~/.ctafconf/etc/shell/alias
fi

if [ -f ~/.ctafconf/perso/kshrc.mine ]; then
    . ~/.ctafconf/perso/kshrc.mine
fi
