#!/bin/sh
## kshrc for ctafconf in /home/ctaf/.ctafconf
##
## Made by GESTES Cedric
## Login   <ctaf@epita.fr>
##
## Started on  Thu Oct  6 04:55:46 2005 GESTES Cedric
## Last update Fri Dec  7 16:06:00 2007 GESTES Cedric
##
##CTAFCONF

# skip remaining setup if shell non-interactive
[[ -o interactive ]] || return 0
[ a$HOST = agate-ssh ] && return 0

cat ~/.config/ctafconf/VERSION
echo -n "shell: ksh, "
cat ~/.config/ctafconf/etc/shell/motd

#date reminder
~/.config/ctafconf/bin/ct-date

# turn on command line editing mode
set -o emacs
#set -o vi-tabcomplete   # tab filename completion ON!

set nobeep

alias source=.

if [ -f ~/.config/ctafconf/etc/ksh/kshprompt ]; then
    . ~/.config/ctafconf/etc/ksh/kshprompt
fi

if [ -f ~/.config/ctafconf/etc/shell/env ]; then
    . ~/.config/ctafconf/etc/shell/env sh
fi

ls ~/.config/ctafconf/perso/env | null_cmd grep '.env$' && source ~/.config/ctafconf/perso/env/*.env


if [ -f ~/.config/ctafconf/etc/shell/alias ]; then
    . ~/.config/ctafconf/etc/shell/alias
fi

if [ -f ~/.config/ctafconf/perso/kshrc.mine ]; then
    . ~/.config/ctafconf/perso/kshrc.mine
fi
