""
" Handling ctafconf profiles

" Read ~/.config/ctafconf/user-profile.sh
" add load ~/.config/ctafconf/profile/<name>/vimrc
" for each name in profile
call ctafconf#load_profiles()

" Last, load ~/.vimrc.user
if has("unix")
  source ~/.vimrc.user
else
  source ~/_vimrc.user
endif

