""
" Sane defaults:

set nocompatible
syntax on
filetype plugin on
set history=10000
set mouse=a
set encoding=utf-8
set showcmd
set showmode
set ruler
set backspace=2
set virtualedit=block
set background=dark
set autowriteall

" nice menu to navigate through possible completions
set wildmenu
" smarter behavior of 'J' (join lines)
set nojoinspaces

" highlight search
set hlsearch

" search as you type
set incsearch
" The correct way to remove highlight is:
" :let @/=""

" Tell NerdCommenter to shut up:
let g:NERDShutUp=1

" Allow completion on filenames right after a '='.
" Uber-useful when editing bash scripts
set isfname-==

" No more annoying bell
set visualbell t_vb=

" Disable useless ctrl+space behavior:
imap <Nul> <Space>

" Always load those useful plugins:
runtime! macros/matchit.vim
runtime! plugin/imaps.vim
runtime! ftplugin/man.vim

" If par is installed, just use it:
if executable("par")
  set formatprg=par
end

" Read ~/.config/ctafconf/user-profile.sh
" add load ~/.config/ctafconf/profile/<name>/vimrc
" for each name in profile
call ctafconf#load_profiles()


" Last, load ~/.vimrc.user
if has("unix")
  source ~/.vimrc.user
else
  source ~/_vimrc.user
endif
