#!/bin/sh
## tcshprompt for ctafconf in /home/ctaf/.ctafconf/etc/tcsh
##
## Made by GESTES Cedric
## Login   <ctaf42@gmail.com>
##
## Started on  Sat Oct  1 00:46:09 2005 GESTES Cedric
## Last update Sat Apr  1 16:04:32 2006 GESTES Cedric
##
##CTAFCONF

##############################
# ##### PROMPT SECTION ##### #
##############################
set rgb_restore   = '%{^[[00m%}'
set rgb_black     = '%{^[[00;30m%}'
set rgb_firebrick = '%{^[[00;31m%}'
set rgb_red       = '%{^[[01;31m%}'
set rgb_forest    = '%{^[[00;32m%}'
set rgb_green     = '%{^[[01;32m%}'
set rgb_brown     = '%{^[[00;33m%}'
set rgb_yellow    = '%{^[[01;33m%}'
set rgb_navy      = '%{^[[00;34m%}'
set rgb_blue      = '%{^[[01;34m%}'
set rgb_purple    = '%{^[[00;35m%}'
set rgb_magenta   = '%{^[[01;35m%}'
set rgb_cadet     = '%{^[[00;36m%}'
set rgb_cyan      = '%{^[[01;36m%}'
set rgb_gray      = '%{^[[00;37m%}'
set rgb_white     = '%{^[[01;37m%}'

set rgb_std       = "${rgb_white}"

if ( ${?root} ) then
    set rgb_usr = "${rgb_red}"
else
    set rgb_usr = "${rgb_yellow}"
endif


if ( ${?prompt} ) set prompt="${rgb_usr}`whoami`${rgb_magenta}@${rgb_brown}`hostname`${rgb_std} ${rgb_magenta}[${rgb_yellow}%?${rgb_magenta}] [${rgb_blue}%~${rgb_magenta}]\
${rgb_white}tc${rgb_usr}%#${rgb_restore} "


unset rgb_*
