#!/bin/sh
## gateway for gateway in /home/gestes_c/bin
## 
## Made by Cedric GESTES
## Login   <gestes_c@epita.fr>
## 
## Started on  Tue Nov  2 17:58:20 2004 Cedric GESTES
## Last update Tue Nov  2 19:18:43 2004 Cedric GESTES
##

if [ $1 = "--help" ]; then
echo 'gateway <gateway ip>'
exit 1;
fi

echo '=>>killing one default route'
sudo /sbin/route del default >/dev/null 2>/dev/null

sudo /sbin/route add default gw $1 metric 1 2>&1

sudo /sbin/ip route
