#!/bin/sh
## zshalias for ctafconf in /ctaf/conf/ctafconf/zsh
##
## Made by root
## Login   <ctaf42@gmail.com>
##
## Started on  Fri Feb 18 01:52:43 2005 root
## Last update Fri Jan  8 01:49:37 2010 Cedric GESTES
##
##CTAFCONF


#source global alias
[ -f ~/.config/ctafconf/etc/shell/alias ] && . ~/.config/ctafconf/etc/shell/alias

#remove autocorrect on those commands:
alias mv='nocorrect mv'
alias cd='nocorrect cd'
alias cp='nocorrect cp'
alias mkdir='nocorrect mkdir'
alias man='nocorrect man'
alias gcc='nocorrect gcc'
alias mkdir='nocorrect mkdir'

autoload zmv
alias mmv='noglob zmv -W'

#no pattern matching (*, etc are not replaced) on those commands:
alias find='noglob find'
alias zmv='noglob zmv'
alias replacer='noglob replacer'

alias -g "..."="../.."
alias -g "...."="../../.."
alias -g "....."="../../../.."


# More useful than pgrep, I believe
function psgrep { ps aux | grep "$*"  | grep -v grep ;}


# Get current IP from checkip.dyndns.org
alias ip="wget http://checkip.dyndns.org/ -O - -o /dev/null | perl -e '<STDIN> =~ m/((\d{1,3}\.){3}\d{1,3})/ && print \"\$1\n\"'"

# Top ten of used commands:
function cmd {
	sed -e 's/sudo //' $HOME/.histfile |  cut -d' ' -f1 | sort | uniq -c | sort -rg | head $1
}


# Stupid extracer:
function xt() {
 if [ -f $1 ]; then
       case $1 in
      *.tar.bz2)   tar xvjf $1     ;;
      *.tar.gz)    tar xvzf $1     ;;
      *.bz2)       bunzip2 $1      ;;
      *.rar)       unrar x $1      ;;
      *.gz)        gunzip $1       ;;
      *.tar)       tar xvf $1      ;;
      *.tbz2)      tar xvjf $1     ;;
      *.tgz)       tar xvzf $1     ;;
      *.zip)       unzip $1        ;;
      *.Z)         uncompress $1   ;;
      *.7z)        7z x $1         ;;
      *)           echo "'$1' cannot be extracted via extract" ;;
    esac
  else
    echo "'$1' is not a valid file"
  fi
}

