#!/bin/sh
## zshalias for ctafconf in /ctaf/conf/ctafconf/zsh
##
## Made by root
## Login   <ctaf42@gmail.com>
##
## Started on  Fri Feb 18 01:52:43 2005 root
## Last update Sun Feb 10 11:03:07 2008 GESTES Cedric
##
##CTAFCONF


#source global alias
[ -f ~/.config/ctafconf/etc/shell/alias ] && . ~/.config/ctafconf/etc/shell/alias

#remove autocorrect on those commands:
alias mv='nocorrect mv'
alias cd='nocorrect cd'
alias cp='nocorrect cp'
alias mkdir='nocorrect mkdir'
alias man='nocorrect man'
alias gcc='nocorrect gcc'
alias mkdir='nocorrect mkdir'

#no pattern matching (*, etc are not replaced) on those commands:
alias find='noglob find'
alias zmv='noglob zmv'
alias replacer='noglob replacer'
