#!/bin/sh
## zshrcctaf for ctafconf in /ctaf/conf/ctafconf/zsh
##
## Made by gestes_c
## Login   <ctaf42@gmail.com>
##
## Started on  Fri Feb 18 01:52:43 2005 GESTES Cedric
## Last update Wed Nov 25 14:16:24 2009 ctaf42
##
##CTAFCONF

#forbit bomb fork (255 is too low)
#on mac 266 is a hardlimit..
limit maxproc 1042 2>/dev/null

#never enter a command already entered once, NEVER!
LISTMAX=10000
#Filename suffixes to ignore during completion
fignore=(.o .c~ .pro)

#OPTIONS
source ~/.config/ctafconf/etc/zsh/zshoptions

#COMPLETION
source ~/.config/ctafconf/etc/zsh/zshstyle

#KEYS
source ~/.config/ctafconf/etc/zsh/zshkeys

#after compinit, dont want which to report alias
disable which
