#!/bin/sh
## zshenv for ctafconf in /ctaf/conf/ctafconf/zsh
##
## Made by GESTES Cedric
## Login   <gestes_c@epita.fr>
##
## Started on  Fri Feb 11 01:37:23 2005 GESTES Cedric
## Last update Thu Feb 15 05:20:43 2007 GESTES Cedric
##
##CTAFCONF


#include global environment
[ -f ~/.config/ctafconf/etc/shell/env ] && . ~/.config/ctafconf/etc/shell/env sh


export HISTSIZE=1000
export HISTFILE=~/.zshhistory
export SAVEHIST=1000
export BLOCK_SIZE=human-readable
# depth of the directory history
DIRSTACKSIZE=30

export SHELL=`which zsh`

#show who login and who logout on the system
export WATCHFMT="%n has %a %l from %M"
export WATCH=all

# Automatically remove duplicates from these arrays
typeset -U PATH

if [ -f ~/.config/ctafconf/perso/zshenv.mine ]; then
    source ~/.config/ctafconf/perso/zshenv.mine
fi
