#!/bin/sh
## zshenv for ctafconf in /ctaf/conf/ctafconf/zsh
##
## Made by GESTES Cedric
## Login   <ctaf42@gmail.com>
##
## Started on  Fri Feb 11 01:37:23 2005 GESTES Cedric
## Last update Tue May 25 19:02:47 2010 Cedric GESTES
##
##CTAFCONF

## Warning ##
#never edit this file
#please edit ~/.zshenv.user


if [[ $- != *i* ]] || [ a$HOST = agate-ssh ]; then
    return
fi

# #disable notification for jobs temporary
# setopt no_monitor

#include global environment
[ -f ~/.config/ctafconf/etc/shell/env ] && . ~/.config/ctafconf/etc/shell/env sh

# #enable notification for jobs
# setopt monitor


export HISTSIZE=50000
export HISTFILE=~/.zshhistory
export SAVEHIST=10000
export BLOCK_SIZE=human-readable
# depth of the directory history
DIRSTACKSIZE=30

export SHELL=`which zsh`

#show who login and who logout on the system
export WATCHFMT="%n has %a %l from %M"
export WATCH=all

# Automatically remove duplicates from these arrays
typeset -U PATH

if [ -f ~/.zshenv.user ]; then
    source ~/.zshenv.user
fi
