#!/bin/sh
## zshoptions for ctafconf in /ctaf/conf/ctafconf/zsh
##
## Made by Cedric GESTES
## Login   <ctaf42@gmail.com>
##
## Started on  Tue Aug 11 14:51:10 2009 Cedric GESTES
## Last update Tue Aug 11 14:52:23 2009 Cedric GESTES
##
##CTAFCONF


###################
## Options Settings (man zshoptions)
###################

#General
setopt no_beep #disable beep in zsh
setopt no_mail_warning

#Completion
setopt correct                 # spelling correction
setopt list_ambiguous          # complete as much of a completion until it gets ambiguous.
setopt norecexact                # recognise exact match even if there are ambiguous matches
setopt complete_aliases
setopt completeinword           # not just at the end
setopt no_always_to_end         # when complete from middle, move cursor

#Menu
#setopt menu_complete		#jump thrue menus
setopt automenu			# don't cycle completions
setopt auto_list
setopt auto_param_keys
setopt auto_param_slash #auto add slash when completing path
setopt auto_remove_slash

setopt equals
setopt magic_equal_subst

setopt numericglobsort
setopt extendedglob             # weird & wacky pattern matching - yay zsh!

#setopt nopromptcr       # don't add \r which overwrites cmd output with no \n
setopt interactivecomments     # date # comment will work

# History handling
setopt append_history           # append to history
setopt inc_append_history       # append immediately
setopt hist_expire_dups_first   # expire duplicates in history first
setopt hist_ignore_all_dups     # don't add dupes to history
setopt hist_verify              # when using ! cmds, confirm first
setopt hist_no_store            # dont add 'history' command (fc -l) to the history
setopt no_bang_hist             #dont redefine ! (commit msg etc often contain !)
### Push History from previous sessions
#fc -R $HISTFILE


# Directory history (use +/- to navigate)
setopt autopushd	      # automatically append dirs to the push/pop list
setopt pushd_minus	      # exchange meaning of + and - for pushd
setopt pushd_silent	      # don't tell me about automatic pushd
setopt pushd_to_home	      # use $HOME when no arguments specified
setopt pushd_ignoredups	      # ignore duplicates
setopt noautocd               # dont change to dirs without cd

