#!/bin/sh
## zshprompt for ctafconf in /ctaf/conf/ctafconf/zsh
##
## Made by GESTES Cedric
## Login   <ctaf42@gmail.com>
##
## Started on  Fri Feb 11 01:37:23 2005 GESTES Cedric
## Last update Tue Feb 13 06:42:01 2007 cedric gestes
##
##CTAFCONF


setprompt () {

    ###
    # Need this so the prompt will work.
    setopt prompt_subst

    ###
    # See if we can use colors.

    autoload colors #zsh/terminfo
#    if [[ "$terminfo[colors]" -ge 8 ]]; then
    colors
 #   fi
    bright="\033[m1;"
    dull="\033[m0;"
    for color in RED GREEN YELLOW BLUE MAGENTA CYAN WHITE; do
	#eval PR_$color='%{$terminfo[bold]$fg[${(L)color}]%}'
	eval PR_$color='%{$fg_no_bold[${(L)color}]%}'
        eval PR_LIGHT_$color='%{$fg_bold[${(L)color}]%}'
	(( count = $count + 1 ))
    done
    PR_NO_COLOUR="%{$terminfo[sgr0]%}"


    ###
    # See if we can use extended characters to look nicer.
#     typeset -A altchar
#     set -A altchar ${(s..)terminfo[acsc]}
#     PR_SET_CHARSET="%{$terminfo[enacs]%}"
#     PR_SHIFT_IN="%{$terminfo[smacs]%}"
#     PR_SHIFT_OUT="%{$terminfo[rmacs]%}"
#     PR_HBAR=${altchar[q]:--}
#     PR_ULCORNER=${altchar[l]:--}
#     PR_LLCORNER=${altchar[m]:--}
#     PR_LRCORNER=${altchar[j]:--}
#     PR_URCORNER=${altchar[k]:--}

###
# Finally, the prompt.
PROMPT='$PR_LIGHT_MAGENTA%(!.%SROOT%s.$PR_LIGHT_WHITE%n$PR_LIGHT_YELLOW)@$PR_LIGHT_GREEN%m$PR_LIGHT_MAGENTA\
 [%(?.$PR_LIGHT_WHITE$?.$PR_LIGHT_RED% err $?)$PR_LIGHT_MAGENTA]\
 [$PR_LIGHT_BLUE%~$PR_LIGHT_MAGENTA]$PR_LIGHT_WHITE\

z$PR_LIGHT_GREEN%(!.#.$)$PR_LIGHT_WHITE '

RPROMPT="[$PR_LIGHT_CYAN%D $PR_LIGHT_GREEN%T$PR_LIGHT_WHITE]"

PS2=''
}

setprompt
