#!/bin/sh
## zshprompt for ctafconf in /ctaf/conf/ctafconf/zsh
##
## Made by GESTES Cedric
## Login   <ctaf42@gmail.com>
##
## Started on  Fri Feb 11 01:37:23 2005 GESTES Cedric
## Last update Tue Aug 11 14:55:09 2009 Cedric GESTES
##
##CTAFCONF

source ~/.config/ctafconf/etc/zsh/zgitinit.zsh
source ~/.config/ctafconf/etc/zsh/prompt_wunjo_setup

export GIT_PROMPT

autoload colors && colors

bright="\033[m1;"
dull="\033[m0;"
for color in BLACK RED GREEN YELLOW BLUE MAGENTA CYAN WHITE; do
	#eval PR_$color='%{$terminfo[bold]$fg[${(L)color}]%}'
  eval export PR_$color='%{$fg_no_bold[${(L)color}]%}'
  eval export PR_BG_$color='%{$bg[${(L)color}]%}'
  eval export PR_LIGHT_$color='%{$fg_bold[${(L)color}]%}'
  (( count = $count + 1 ))
done
PR_NO_COLOUR="%{$terminfo[sgr0]%}"

git_prompt() {
  if zgit_isgit ; then
# $(prompt_wunjo_scm_branch)
    echo "${PR_BG_BLACK}[GIT$(prompt_wunjo_scm_status)]$PR_NO_COLOUR"
    echo "\r"
  fi
}


setprompt () {

  # Need this so the prompt will work.
  setopt prompt_subst

    ###
    # See if we can use extended characters to look nicer.
#     typeset -A altchar
#     set -A altchar ${(s..)terminfo[acsc]}
#     PR_SET_CHARSET="%{$terminfo[enacs]%}"
#     PR_SHIFT_IN="%{$terminfo[smacs]%}"
#     PR_SHIFT_OUT="%{$terminfo[rmacs]%}"
#     PR_HBAR=${altchar[q]:--}
#     PR_ULCORNER=${altchar[l]:--}
#     PR_LLCORNER=${altchar[m]:--}
#     PR_LRCORNER=${altchar[j]:--}
#     PR_URCORNER=${altchar[k]:--}


PROMPT='$(git_prompt)\
$PR_BG_BLACK\
$PR_LIGHT_MAGENTA%(!.%SROOT%s.$PR_LIGHT_WHITE%n$PR_LIGHT_YELLOW)@$PR_LIGHT_GREEN%m$PR_LIGHT_MAGENTA\
 [%(?.$PR_LIGHT_WHITE$?.$PR_LIGHT_RED% err %?)$PR_LIGHT_MAGENTA]\
 [$PR_LIGHT_BLUE%~$PR_LIGHT_MAGENTA]$PR_NO_COLOUR\

z$PR_LIGHT_GREEN%(!.#.$)\
$PR_NO_COLOUR '

RPROMPT="[$PR_BG_BLACK$PR_LIGHT_CYAN%D $PR_LIGHT_GREEN%T$PR_NO_COLOUR]"

PS2=''
}

prompt_wunjo_setup
setprompt
