#!/bin/sh
## zshrc.linux for ctafconf in /ctaf/conf/ctafconf/zsh
##
## Made by GESTES Cedric
## Login   <ctaf42@gmail.com>
##
## Started on  Fri Feb 11 01:37:23 2005 GESTES Cedric
## Last update Tue Aug 11 14:56:10 2009 Cedric GESTES
##
##CTAFCONF

## Warning ##
#never edit this file
#please edit ~/.config/ctafconf/perso/zshrc.mine

#to start a clean zsh session (without conf) : zsh -fx

# Shell is non-interactive.  Be done now
if [[ $- != *i* ]] || [ a$HOST = agate-ssh ]; then
    return
fi

cat ~/.config/ctafconf/VERSION
echo -n "shell: zsh, "
cat ~/.config/ctafconf/etc/shell/motd

#alias
. ~/.config/ctafconf/etc/zsh/zshalias

#General config
. ~/.config/ctafconf/etc/zsh/zshconf

#Prompt
if [ x$ctafconf_zprompt = x ] || [ x$ctafconf_zprompt = xctaf ] ; then
  source ~/.config/ctafconf/etc/zsh/zshprompt
else
  autoload -U promptinit
  promptinit
  prompt $ctafconf_zprompt
fi

if [ -f ~/.config/ctafconf/perso/zshrc.mine ]; then
  source ~/.config/ctafconf/perso/zshrc.mine
fi
