#!/bin/sh
## zshrc.linux for ctafconf in /ctaf/conf/ctafconf/zsh
##
## Made by GESTES Cedric
## Login   <gestes_c@epita.fr>
##
## Started on  Fri Feb 11 01:37:23 2005 GESTES Cedric
## Last update Sat Feb 17 02:19:03 2007 GESTES Cedric
##
##CTAFCONF

# Shell is non-interactive.  Be done now
if [[ $- != *i* ]] || [ a$HOST = agate-ssh ]; then
    return
fi
cat ~/.ctafconf/VERSION
echo -n "shell: zsh, "
cat ~/.ctafconf/etc/shell/motd

#date reminder
~/.ctafconf/bin/ct-date

#alias
. ~/.ctafconf/etc/zsh/zshalias

#General config
. ~/.ctafconf/etc/zsh/zshconf

. ~/.ctafconf/etc/shell/shfunction
#Prompt
if [ x$ctafconf_zprompt = x ] || [ x$ctafconf_zprompt = xctaf ] ; then
    source ~/.ctafconf/etc/zsh/zshprompt
else
    autoload -U promptinit
    promptinit
    prompt $ctafconf_zprompt
fi

if [ -f ~/.ctafconf/perso/zshrc.mine ]; then
    source ~/.ctafconf/perso/zshrc.mine
fi
