" Remove need from Escape key:
" map jj in insert mode to go to normal mode
" (note going to normal mode from other modes is always
" possible with ctrl+c)
inoremap jj <ESC>
vnoremap jj <ESC>

" Remove menu bar from GUI
let did_install_default_menus = 1

" Remove trailing whitespaces when saving:
autocmd bufwritepre * :%s/\s\+$//e

" Tabulations
set shiftwidth=2
set expandtab
set smarttab
set smartindent
set tabstop=4



" Status line
set laststatus=2
set statusline=%{VimBuddy()}\ %<%f\ %h%m%r%=%-14.(%l,%c%V%)\ %P


""
" Few keybindings

" 'cd' towards the dir in which the current file is edited
" but only change the path for the current window
map ,cd :lcd %:h<CR>

" I prefer , for mapleader rather than \
let mapleader=","

" Open files located in the same dir in with the current file is edited
map <leader>ew :e <C-R>=expand("%:p:h") . "/" <CR>
map <leader>es :sp <C-R>=expand("%:p:h") . "/" <CR>
map <leader>ev :vsp <C-R>=expand("%:p:h") . "/" <CR>
map <leader>et :tabe <C-R>=expand("%:p:h") . "/" <CR>

" Navigate through the buffer's list with alt+up, alt+down
nnoremap <M-Down>  :bp<CR>
nnoremap <M-Up>    :bn<CR>

" Man page for work under cursor
nnoremap K :Man <cword> <CR>
" Spell check
cmap spc setlocal spell spelllang=

" Bubble single lines
nmap <C-Up> ddkP
nmap <C-Down> ddp

" Bubble multiple lines
vmap <C-Up> xkP`[V`]
vmap <C-Down> xp`[V`]

""
" Skeletons :

" First read the skeleton ...
autocmd BufNewFile *.rb        0r ~/.config/ctafconf/etc/vim/skeletons/rbskel.rb
autocmd BufNewFile *.sh        0r ~/.config/ctafconf/etc/vim/skeletons/shskel.sh
autocmd BufNewFile *.tex       0r ~/.config/ctafconf/etc/vim/skeletons/texskel.tex
autocmd BufNewFile *.py        0r ~/.config/ctafconf/etc/vim/skeletons/pyskel.py
autocmd BufNewFile *.html      0r ~/.config/ctafconf/etc/vim/skeletons/htmlskel.html

" ... then move to the according line
autocmd BufNewFile *.rb       :3
autocmd BufNewFile *.sh       :3
autocmd BufNewFile *.tex      :16
autocmd BufNewFile *.html     :12

""
" Misc

" I always make mistakes in these words
abbreviate swith switch
abbreviate wich which
abbreviate lauch launch
