##
## Cutom settings for Zsh
##

# Activate spell check:
setopt correct

# Activate bang history:
setopt bang_hist

# Better safe that sorry:
alias_set rm "rm -i"
alias_set mv "mv -iv"
alias_set cp "cp -iv"

# ./foo.mp3 will open the file with mplayer,
# and so on:
alias -s mp3=mplayer
alias -s avi=mplayer
alias -s pdf=evince
alias -s html=firefox

# Add $HOME/bin to path:
# (pretty standard)
export PATH="$PATH:$HOME/bin"

