#!/bin/sh
## alias for alias in /home/ctaf/.ctafconf/etc
##
## Made by GESTES Cedric
## Login   <ctaf@epita.fr>
##
## Started on  Fri Sep 30 22:17:52 2005 GESTES Cedric
## Last update Tue Oct  4 14:49:19 2005 GESTES Cedric
##
##CTAFCONF

####
## SET equal to " " (tcsh) or "=" (zsh,bash)
## UNSET
####

###
#global alias
#used by all shell (zsh, bash, ksh, tcsh)
##

#use + and - to navigate thru cd's dir history
alias -- +$sh_aliaseq'pushd +0'
alias -- -$sh_aliaseq'pushd -1'

#############################
#COMPILATION ALIAS
#############################
alias m$sh_aliaseq'make'
alias md$sh_aliaseq'make distclean'
alias ma$sh_aliaseq'make clean all'
alias mac$sh_aliaseq'make clean all check'
alias c$sh_aliaseq'./configure'
alias gm$sh_aliaseq'gmake'

#default alias for firefox and thunderbird
alias ff$sh_aliaseq'firefox'
alias tb$sh_aliaseq'thunderbird'

#wget recursif
#alias wgetr$sh_aliaseq'wget -r -N -l inf --connect-timeout=10'
alias wgetr$sh_aliaseq'wget -r -N -l inf'

#recursive grep with filename and line number
alias grepr$sh_aliaseq'grep -r -n -H'

#remove directory
alias rd$sh_aliaseq'rm -r'

#emacs alias
alias e$sh_aliaseq'emacs'
#emacs en console
alias enox$sh_aliaseq'emacs -nw'
alias ne$sh_aliaseq'emacs -nw'

alias z$sh_aliaseq"zsh"
alias b$sh_aliaseq"bash"

#change the user::group of all the file in the home user directory
alias chownhome$sh_aliaseq'$ctafconf_sudo chown -R $ctafconf_user:$ctafconf_group ~/'

#image en fullscreen
alias full$sh_aliaseq'xv -maxpect'

#vim
alias vi$sh_aliaseq'vim'

#ghostview
alias gv$sh_aliaseq"gv -resize -center -antialias"
alias xfig$sh_aliaseq'xfig -metric -startgridmode 1'
alias less$sh_aliaseq'less -r -X -M'

#alias make$sh_aliaseq'gmake'
alias mm$sh_aliaseq'make |& less'
alias make_muet$sh_aliaseq"make 1>/dev/null"

alias netscape$sh_aliaseq"rm ~/.netscape/lock 2>/dev/null ; netscape &!"

alias getx$sh_aliaseq'export DISPLAY=:0.0'

alias j$sh_aliaseq'jobs'
alias h$sh_aliaseq'history'

alias a1$sh_aliaseq'ns_who -asgl | grep a1 | grep sm-'
alias a2$sh_aliaseq'ns_who -asgl | grep a2 | grep sm-'
alias a3$sh_aliaseq'ns_who -asgl | grep a3 | grep sm-'

alias reports$sh_aliaseq"w3m http://www.lrde.epita.fr/~akim/compil/reports.html"
alias compil$sh_aliaseq"w3m http://www.lrde.epita.fr/~akim/compil/"
#alias gnus$sh_aliaseq'LC_CTYPE=fr_FR emacs -f gnus'
alias gnus$sh_aliaseq'emacs -nw -f gnus'
alias fixme$sh_aliaseq'grep -n -a -s FIXME * 2> /dev/null'

###########################################
# Global aliases -- These do not have to be
# at the beginning of the command line.
###########################################
#alias -g M$sh_aliaseq'|more'
#alias -g H$sh_aliaseq'|head'
#alias -g T$sh_aliaseq'|tail'
#alias -g tcopt$sh_aliaseq"--types-check --hir-compute --hir-display" ## For Tiger

alias svctaf$sh_aliaseq'svn co svn+ssh://ctaf@elthariel.no-ip.org/home/ctaf/svn/.ctafconf'


alias ls$sh_aliaseq'ls -F --color=tty'

#sourcing plateform spécifik
test x$ctafconf_config != x && test -f ~/.ctafconf/etc/shell/alias.$ctafconf_config && source ~/.ctafconf/etc/shell/alias.$ctafconf_config


#AFTER HERE
#PLATFORM SPECIFIC STUFF IS USED

alias l$sh_aliaseq'ls -F --color=tty'
alias ll$sh_aliaseq'ls -lF --color=tty'
alias la$sh_aliaseq'ls -lAF --color=tty'
