#!/bin/sh
## alias for alias in /home/ctaf/.ctafconf/etc
##
## Made by GESTES Cedric
## Login   <ctaf42@gmail.com>
##
## Started on  Fri Sep 30 22:17:52 2005 GESTES Cedric

##
##CTAFCONF

###
#global alias
#used by all shell (zsh, bash)
##

#use + and - to navigate thru cd's dir history
alias_set + 'pushd +0'
alias_set - 'pushd -1'

#############################
#COMPILATION ALIAS_SET
#############################
alias c='./configure'
alias a='autoreconf -isvf'
alias smi='sudo make install'
alias m='~/.config/ctafconf/bin/colorwarper make'
alias md='~/.config/ctafconf/bin/colorwarper make distclean'
alias ma='~/.config/ctafconf/bin/colorwarper make clean all'
alias mac='~/.config/ctafconf/bin/colorwarper make clean all check'
alias gm='~/.config/ctafconf/bin/colorwarper gmake'
alias mm='~/.config/ctafconf/bin/colorwarper make |& less'
alias make_mute="~/.config/ctafconf/bin/colorwarper make 1>/dev/null"
alias fixme='grep -n -a -s FIXME * 2> /dev/null'
alias todo='grep -n -a -s TODO * 2> /dev/null'
alias svndiff='svn diff --diff-cmd `which diff` -x "-w -E -u -B -b"'
alias svn_real='`which svn`'
alias svn='~/.config/ctafconf/bin/colorwarper svn'
alias cvs_real='`which svn`'
alias cvs='~/.config/ctafconf/bin/colorwarper cvs'
alias make='~/.config/ctafconf/bin/colorwarper make'
alias make_real='`which make`'
alias gmake='~/.config/ctafconf/bin/colorwarper gmake'
alias gmake_real='`which gmake`'
alias ka='killall'
alias doxygen='~/.config/ctafconf/bin/colorwarper doxygen'
#alias make='gmake'

# Quick chmod
alias 644='chmod 644'
alias 755='chmod 755'

#default alias_set for firefox and thunderbird

null_which mozilla-firefox && alias ff='mozilla-firefox'
null_which firefox && alias ff='firefox'

null_which mozilla-firefox && alias cf='mozilla-firefox -chrome chrome://conkeror/content'
null_which firefox && alias cf='firefox -chrome chrome://conkeror/content'

null_which mozilla-thunderbird && alias tb='mozilla-thunderbird'
null_which thunderbird && alias tb='thunderbird'


#wget recursif
#alias wgetr='wget -r -N -l inf --connect-timeout=10'
#-r recursif
#-N timestamping
#-l inf : recursion depth
#-c continue
#-np no parent => don't download parent directory
#-nH no hostname => wgetr ftp.free.fr/bob/ => ./bob/
#-p get all files needed in order to render the html page completely
#--convert-links
alias wgetr='wget -r -N -l inf -c -np'
alias wgetr_localhtml='wget -r -N -l inf -c -np --convert-links -p'

#remove directory
alias rd='rm -r'
alias rmrf='rm -rf'

#emacs alias_set
alias e='emacs'
#emacs en console
alias ne='emacs -nw'

#vim
null_which vim && alias vi= 'vim'
null_which vim && alias svi='sudo vim'

# Screen is nice but options can be a bit hard to remember:
alias sw='screen -wipe'
alias sr='screen -RaAd'

# Get current IP from checkip.dyndns.org
alias myip="wget http://checkip.dyndns.org/ -O - -o /dev/null | perl -e '<STDIN> =~ m/((\d{1,3}\.){3}\d{1,3})/ && print \"\$1\n\"'"


alias z="zsh"
alias b="bash"
alias k="ksh"
alias t="tcsh"

alias psa='ps ax'
alias psu='ps aux'
alias psgrep='ps aux | grep -v grep | grep'

#change the user::group of all the file in the home user directory
alias chownr='chown -R $USER:`id -g -n`'
alias cux=   'chmod +x'

#image en fullscreen
alias full='xv -maxpect'

#ghostview
alias less='less -r -X -M'

alias getx='export DISPLAY=:0.0'

alias h='history'

#never alias ls
#alias ls='ls -F --color=tty'

alias sudo_real='`which sudo`'
alias sudo='sudo -H'

#find a .env file
sz-find-env()
{
  cur_dir=$(pwd)/fake
  while true; do
    cur_dir=$(dirname ${cur_dir})
    if [ -f "${cur_dir}/.env" ]; then
      echo "${cur_dir}/.env"
      return;
    fi
    if [ "${cur_dir}" = "/" ] || [ -z "${cur_dir}" ] ; then
      break
    fi
  done
  return 1
}
#source a .env found in the current or parents directory
alias sz='sz-find-env >/dev/null && source $(sz-find-env)'


#AFTER HERE
#PLATFORM SPECIFIC STUFF IS USED

alias l='ls -F --color=auto'
alias ls='ls -F --color=auto'
alias ll='ls -lF --color=auto'
alias la='ls -lAF --color=auto'
alias lg='ls -F --color=auto | grep'

alias grep='grep --color=auto'
alias grep_real='`which grep`'

#different plateform test
test -f ~/.config/ctafconf/etc/shell/alias.`uname` && source ~/.config/ctafconf/etc/shell/alias.`uname`

# #sourcing plateform specific
# test x$ctafconf_config != x && test -f ~/.config/ctafconf/etc/shell/alias.$ctafconf_config && source ~/.config/ctafconf/etc/shell/alias.$ctafconf_config

#protect ls against failure
ls ~/.config/ctafconf 2>/dev/null >/dev/null || unalias ls
