#!/bin/sh
## alias for alias in /home/ctaf/.ctafconf/etc
##
## Made by GESTES Cedric
## Login   <ctaf@epita.fr>
##
## Started on  Fri Sep 30 22:17:52 2005 GESTES Cedric
## Last update Fri Mar 31 20:44:51 2006 GESTES Cedric
##
##CTAFCONF

####
## SET equal to " " (tcsh) or "=" (zsh,bash)
## UNSET
####

###
#global alias
#used by all shell (zsh, bash, ksh, tcsh)
##

#use + and - to navigate thru cd's dir history
alias_set + 'pushd +0'
alias_set - 'pushd -1'

#############################
#COMPILATION ALIAS_SET
#############################
alias_set c './configure'
alias_set a './autogen.sh'
alias_set m 'make'
alias_set md 'make distclean'
alias_set ma 'make clean all'
alias_set mac 'make clean all check'
alias_set gm 'gmake'
alias_set mm 'make |& less'
alias_set make_muet "make 1>/dev/null"
alias_set fixme 'grep -n -a -s FIXME * 2> /dev/null'
alias_set todo 'grep -n -a -s TODO * 2> /dev/null'
#alias_set make 'gmake'

#default alias_set for firefox and thunderbird

which mozilla-firefox >/dev/null && alias_set ff 'mozilla-firefox'
which firefox >/dev/null && alias_set ff 'firefox'

which mozilla-firefox >/dev/null&& alias_set cf 'mozilla-firefox -chrome chrome://conkeror/content'
which firefox >/dev/null && alias_set cf 'firefox -chrome chrome://conkeror/content'

which mozilla-thunderbird >/dev/null && alias_set tb 'mozilla-thunderbird'
which thunderbird >/dev/null && alias_set tb 'thunderbird'


#wget recursif
#alias_set wgetr 'wget -r -N -l inf --connect-timeout=10'
#-r recursif
#-N timestamping
#-l inf : recursion depth
#-c continue
#-np no parent => don't download parent directory
#-nH no hostname => wgetr ftp.free.fr/bob/ => ./bob/
#-p get all files needed in order to render the html page completely
#--convert-links
alias_set wgetr 'wget -r -N -l inf -c -np'
alias_set wgetr_localhtml 'wget -r -N -l inf -c -np --convert-links -p'

#recursive grep with filename and line number
alias_set grepr 'grep -r -n -H'

#remove directory
alias_set rd 'rm -r'

#emacs alias_set
alias_set e 'emacs'
#emacs en console
alias_set enox 'emacs -nw'
alias_set ne 'emacs -nw'
#alias_set gnus 'LC_CTYPE=fr_FR emacs -f gnus'
alias_set gnus 'emacs -nw -f gnus'

alias_set z "zsh"
alias_set b "bash"
alias_set k "ksh"
alias_set t "tcsh"

alias_set psa 'ps -ax'
alias_set psu 'ps -aux'

#change the user::group of all the file in the home user directory
alias_set chownhome '$ctafconf_sudo chown -R $USER:`id -g -n` ~/'

#image en fullscreen
alias_set full 'xv -maxpect'

#vim
alias_set vi 'vim'

#ghostview
alias_set gv "gv -resize -center -antialias_set"
alias_set xfig 'xfig -metric -startgridmode 1'
alias_set less 'less -r -X -M'

alias_set getx 'export DISPLAY=:0.0'

alias_set j 'jobs'
alias_set h 'history'

#VNC
alias_set ct-tightvnc 'xtightvncviewer -bgr233 -compresslevel 9 -quality 0 -depth 8 -owncmap -encodings tight'
alias_set ct-vnc 'xvnc4viewer'


alias_set ls 'ls -F --color=tty'

#sourcing plateform spécifik
test x$ctafconf_config != x && test -f ~/.ctafconf/etc/shell/alias.$ctafconf_config && source ~/.ctafconf/etc/shell/alias.$ctafconf_config


#AFTER HERE
#PLATFORM SPECIFIC STUFF IS USED

alias_set l 'ls -F --color=tty'
alias_set ll 'ls -lF --color=tty'
alias_set la 'ls -lAF --color=tty'
alias_set lg 'ls -F --color=tty | grep'

###UNUSED UN-USEFULL###
#alias_set reports "w3m http://www.lrde.epita.fr/~akim/compil/reports.html"
#alias_set compil "w3m http://www.lrde.epita.fr/~akim/compil/"
#alias_set svctaf 'svn co svn+ssh://ctaf@elthariel.no-ip.org/home/ctaf/svn/.ctafconf'
#alias_set netscape "rm ~/.netscape/lock 2>/dev/null ; netscape &!"
###########################################
# Global aliases -- These do not have to be
# at the beginning of the command line.
###########################################
#alias -g M='|more'
#alias -g H='|head'
#alias -g T='|tail'
