#!/bin/sh
## env for env in /home/ctaf/.ctafconf/etc
##
## Made by GESTES Cedric
## Login   <ctaf@epita.fr>
##
## Started on  Fri Sep 30 22:17:33 2005 GESTES Cedric
## Last update Tue Oct  4 17:55:53 2005 GESTES Cedric
##
##CTAFCONF

##need sh_sh sh_csh sh_export

##include CTAFCONF INFORMATION
test -f ~/.ctafconf/user-profile || echo "###############################################################"
test -f ~/.ctafconf/user-profile || echo "##### CTAFCONF: Cant find ~/.ctafconf/user-profile        #####"
test -f ~/.ctafconf/user-profile || echo "##### CTAFCONF: This file contain the user information    #####"
test -f ~/.ctafconf/user-profile || echo "##### CTAFCONF: needed by the ctafconf                    #####"
test -f ~/.ctafconf/user-profile || echo "##### CTAFCONF: You can manage this file with: ct-profile #####"
test -f ~/.ctafconf/user-profile || echo "###############################################################"
# else
test x$sh_export = "xexport" && test -f ~/.ctafconf/user-profile && . ~/.ctafconf/user-profile

test x$sh_export = "xsetenv" && test -f ~/.ctafconf/user-profile.csh && source ~/.ctafconf/user-profile.csh

# fi

###############################
## Environment variables export
###############################
$sh_export TERM$sh_exporteq"xterm"
$sh_export COLORTERM$sh_exporteq"xterm"
#shell for XTERM

$sh_export SHELL$sh_exporteq`which zsh`

$sh_export LS_COLORS$sh_exporteq'no=00:fi=00:di=0;33:ln=01;36:pi=40;33:so=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.gz=01;31:*.bz2=01;31:*.deb=01;31:*.rpm=01;31:*.jpg=01;35:*.gif=01;35:*.bmp=01;35:*.pgm=01;35:*.pbm=01;35:*.ppm=01;35:*.tga=01;35:*.png=01;35:*.GIF=01;35:*.JPG=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.mpg=01;37:*.avi=01;37:*.gl=01;37:*.dl=01;37:*.mly=01;37:*.mll=01;37:*.mli=01;37:*.ml=01;37:*.cpp=01;37:*.cc=01;37:*.c=01;37:*.hh=01;37:*.h=01;37:*Makefile=4;32:*.pl=4;32:*.sh=4;32:*.ps=4;34:*.pdf=4;34:*.txt=01;37:*.tex=01;37:*TODO=01;37'

#$sh_export LANG=ja_JP.eucJP
#$sh_export LC_CTYPE$sh_exporteq$LANG
#$sh_export LC_ALL$sh_exporteq$LANG
#$sh_export XMODIFIERS$sh_exporteq"@im$sh_exporteqkinput2" #for japanese input

$sh_export NNTPSERVER$sh_exporteq'news.epita.fr'

#specify the socks global variable (for runsocks, )
$sh_export SOCKS5_SERVER$sh_exporteq'socks:1080'
$sh_export SOCKS5_USER$sh_exporteq"$ctafconf_login"
$sh_export SOCKS5_PASSWD$sh_exporteq"$ctafconf_home"/.socks

#specify proxy (for apt, )
$sh_export http_proxy$sh_exporteq #http://localhost:3128/
$sh_export ftp_proxy$sh_exporteq #http://localhost:3128/


$sh_export FULLNAME$sh_exporteq"$ctafconf_name"
$sh_export REALNAME$sh_exporteq"$ctafconf_name"


$sh_export EADNULLCMD$sh_exporteq'less'
$sh_export EMAIL$sh_exporteq"$ctafconf_mail"
$sh_export MAIL$sh_exporteq"/var/mail/$ctafconf_login"

#for debian
$sh_export DEBEMAIL$sh_exporteq"$ctafconf_mail"


#option for less
$sh_export LESS$sh_exporteq"-cex3M"

#text editor in console mode
$sh_export VISUAL$sh_exporteq"emacs"
$sh_export EDITOR$sh_exporteq"emacs"

#used by man, ..
$sh_export PAGER$sh_exporteq"less"

#cvs variable
$sh_export CVS_RSH$sh_exporteq"ssh"

# if [ -d /usr/pkg/lib ]; then
#     export LD_LIBRARY_PATH$sh_exporteq$LD_LIBRARY_PATH:/usr/pkg/lib
# fi


#SETTING PATH
test -d /usr/sbin && $sh_export PATH$sh_exporteq"$PATH":/usr/sbin
test -d /sbin && $sh_export PATH$sh_exporteq"$PATH":/sbin

#[ -d /usr/pkg/bin  && PATH$sh_exporteq$PATH:/usr/pkg/bin
#test -d ~/.ctafconf/bin && PATH$sh_exporteq"$PATH:~/.ctafconf/bin"
test -d ~/.ctafconf/bin && $sh_export PATH$sh_exporteq"$PATH":$ctafconf_home/.ctafconf/bin:.


#sourcing plateform spécifik
test x$ctafconf_config != x && test -f ~/.ctafconf/etc/shell/globalenv.$ctafconf_config && . ~/.ctafconf/etc/shell/globalenv.$ctafconf_config
